kind: pipeline
type: docker
name: test

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: saud009/golang-bankapi
      tags: latest
      debug: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BUILDKIT_INLINE_CACHE=1
    when:
      event:
        - push
      branch:
        - master

  - name: run-tests
    image: golang:latest
    commands:
      - echo "Running tests..."
      - go test -v ./...
      - echo "Tests completed successfully."

trigger:
  event:
    - push
    - cron
    - custom
