kind: pipeline
type: docker
name: test

steps:
  - name: build
    image: docker:latest
    services:
      - name: docker
        image: docker:dind
        privileged: true
    commands:
      - echo "Building Docker image..."
      - docker build -t saud009/golang-bankapi:latest .
      - echo "Docker image built successfully."

  - name: run-tests
    image: golang:latest
    commands:
      - echo "Running tests..."
      - go test -v ./...
      - echo "Tests completed successfully."

  - name: publish
    image: plugins/docker
    settings:
      repo: saud009/golang-bankapi
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
      debug: true

trigger:
  event:
    - push
    - cron
    - custom
